source 'http://rubygems.org'

gem 'rails', '~> 4.2.2'
gem 'haml', '~> 4.0.6'
gem 'thin', '~> 1.6.3'
gem 'active_link_to'
gem 'simple_form'
gem 'foundation-rails', '~> 5.5.2'
gem 'jquery-rails', '~> 4.0.4'
gem 'uglifier', '~> 2.7.1'
